### ISSUE TITLE
Name conflict

### ISSUE THREAD

**Issue by PalmerAL** [Kyome22/Telescopure#2]
Hello, I'm the maintainer of [Min](https://github.com/minbrowser/min). We've been around since 2015 and have several thousand users. Although we do not currently have a mobile version, we may in the future. So that people are not confused, would you be open to changing the name of your app?

**Comment by Kyome22** [comment]
@PalmerAL  Thank you for contacting me.
I only did market research on the AppStore and didn't know about Min.
Therefore, I unintentionally gave it a similar name.
Since MinBrowser has already been released on the AppStore, I would like to avoid changing it if possible because it would be quite costly to change.
I don't think the problem is serious enough to change it since the names are not exactly the same, but what do you think?
(In fact, I think this degree of overlap is common in the app market.)

**Comment by Kyome22** [comment]
@PalmerAL 
After thinking about it a lot, I decided to change the name.
Rename MinBrowser to Telescopure. It's a completely coined word.
It will take some time for the rename to be reflected as it will need to be submitted to the AppStore.

**Comment by PalmerAL** [comment]
Thank you for doing that; I know it can take a fair amount of work to do, but this should avoid any confusion for users. That seems like a good name; I wish you luck with the project.
